### ISSUE TITLE
Feature Request: 自动深色主题、自适应图标

### ISSUE THREAD

**Issue by ZeppLu** [ykrank/S2Goose#11]
感谢开发者的辛苦工作。使用过程中发现了两处可完善的小地方，希望能考虑一下
1. 虽然鹅球提供了黑色乃至A屏黑的主题，但目前还没有[跟随系统主题设置](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#%E6%9B%B4%E6%94%B9%E5%BA%94%E7%94%A8%E5%86%85%E4%B8%BB%E9%A2%98%E8%83%8C%E6%99%AF)、自动切换白天/夜间主题的功能
2. 反编译看了下，鹅球图标似乎没有做[自适应图标](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)，导致在非圆形的图标中会有一圈白色背景，显得很突兀

![SmartSelect_20211029-191121_One UI Home.jpg](https://i.loli.net/2021/10/29/4BEtjcGnCqlUz8u.jpg)

**Comment by ZeppLu** [comment]
sorry看错了，原来这里是新的flutter客户端。不过还是希望旧的S1 next goose能继续更新，或者把最新版本开源出来

**Comment by ykrank** [comment]
新鹅球做了自适应图标，原来的旧鹅球做了部分的自适应，主要是因为为了照顾到这是个台球，外面只能是圆的，因此只好加了白边

**Comment by ykrank** [comment]
最新代码未开源是因为没时间去重构，目前代码里面有些私有化信息，这个可以等待新鹅球发布后我抽出点时间
