### ISSUE TITLE
功能需求：①列表显示简略模式 ②主界面板块分类展开/收起状态的记忆 ③板块入口顶置

### ISSUE THREAD

**Issue by pgain2004** [ykrank/S2Goose#5]
1、在右侧抽屉提供快速设置，去掉板块列表里基本没人看的板块介绍，去掉主题列表除发帖人、回复和新增回复外所有其它信息（如 _**标题XXXXXXXXX [发帖者] 回复数(+新增回复数)**_ ），参考旧鹅球，这样可以一次浏览更多内容

2、例如我之前收起了“热门新区”，则下次回到主页它仍然是收起状态

3、在主页长按某个板块弹出菜单，可让它顶置。如果实现了该功能，则上面的需求②和需求①中的精简都可以忽略

**Comment by ykrank** [comment]
没产品经理，暂不做这么细的UI调整。
主题列表或许可以找时间优化

**Comment by pgain2004** [comment]
其它都不做的话只做状态记忆或者顶置都行啊

**Comment by ykrank** [comment]
> 其它都不做的话只做状态记忆或者顶置都行啊

就这几个板块，也需要置顶么？

**Comment by ykrank** [comment]
考虑了一下，主题列表优化和收藏板块可以做。优先度看缘分

**Comment by ykrank** [comment]
Done
